# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='cost',
            new_name='availability',
        ),
    ]
