# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180522_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionalinformation',
            options={'verbose_name_plural': 'Nutrional Information'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
