# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_cooking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='recipes.Recipe'),
        ),
    ]
