# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20180522_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='availability',
            field=models.CharField(choices=[(b'LO', b'Locally'), (b'ON', b'Online'), (b'EX', b'Exotic')], max_length=2),
        ),
    ]
