# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20180522_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='key_ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[(b'SO', b'Soups'), (b'DR', b'Desserts'), (b'AZ', b'Appetizers'), (b'MN', b'Main Course'), (b'SD', b'Side Dishes'), (b'CD', b'Condiments'), (b'SC', b'Snacks'), (b'BG', b'Beverages')], default=b'MN', max_length=2),
        ),
    ]
