# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0006_auto_20180522_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mealplan',
            },
        ),
        migrations.CreateModel(
            name='MealPlanMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[(b'SU', b'Sun'), (b'MO', b'Mon'), (b'TE', b'Tues'), (b'WD', b'Wed'), (b'TR', b'Thurs'), (b'FR', b'Fri'), (b'ST', b'Sat')], max_length=2)),
                ('meal', models.CharField(choices=[(b'BK', b'Breakfast'), (b'LN', b'Lunch'), (b'DN', b'Dinner'), (b'SK', b'Snacks'), (b'DR', b'Dessert')], max_length=2)),
                ('approx_calorie_count', models.PositiveIntegerField(default=0)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealplan', to='mealplans.MealPlan')),
                ('recipes', models.ManyToManyField(related_name='mealplan_recipes', to='recipes.Recipe')),
            ],
            options={
                'db_table': 'mealplan_menu',
                'verbose_name_plural': 'MealPlan Menu',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mealplanmenu',
            unique_together=set([('day', 'meal_plan', 'meal')]),
        ),
    ]
